spring.application.name=sp04

# datasource : DBMS, Oracle
spring.datasource.driver-class-name= oracle.jdbc.OracleDriver
spring.datasource.url= jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username= hr
spring.datasource.password= hr

#Mybatis config
# Settings => mybatis.configuration
mybatis.configuration.map-underscore-to-camel-case = true
mybatis.configuration.jdbc-type-for-null=NULL
# typeAliases => mybatis.type-aliases-XXX
mybatis.type-aliases-package = com.yedam.app
# mapper => mybatis.mapper-locations
mybatis.mapper-locations = classpath:mapper/*.xml

#log
logging.level.com.yedam.app=debug   


